#spring:
 # data:
 #   mongodb:
  #    host: localhost
  #    port: 27017
  #    database: prototypeactions
  #    username: ${DATASOURCE_USERNAME:admin}
  #    password: ${DATASOURCE_PASSWORD:adminpw}
  #    authentication-database: admin
  #   auto-index-creation: true

#de:
  #flapdoodle:
    #mongodb:
      #embedded:
        #version: 4.4.18 #6.0.5
        #storage:
          #repl-set-name: rs0
        