spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: prototypeactions
      username: ${DATASOURCE_USERNAME:admin}
      password: ${DATASOURCE_PASSWORD:adminpw}
      authentication-database: admin
      auto-index-creation: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: "prototype_availability" 

     