server:
  port: 8081
  #use-forward-headers: true
  #forward-headers-strategy: framework
  servlet:
    context-path: /${spring.application.name}
spring:
   application:
    name: nsp-archetype-cqrs-ev-cmd
   profiles:
     active: dev
   config:
     import: "classpath:/application-dev.yml"

management:
  endpoints:
    web:
      #base-path: /ocp-nsp-sorteo
      exposure:
        #include: '*'
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
   tags:
    application: ${spring.application.name}