server:
  port: 8081
  #use-forward-headers: true
  #forward-headers-strategy: framework
  servlet:
    context-path: /${spring.application.name}
spring:
   application:
    name: archetype-cqrs-ev-cmd
   profiles:
     active: dev
   config:
     import: "classpath:/application-dev.yml"

management:
  tracing:
    sampling:
      probability: 1.0  
  endpoints:
    web:
      #base-path: /ocp-nsp-sorteo
      exposure:
        #include: '*'
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
   tags:
    application: ${spring.application.name}
  otlp:
      tracing:
          #endpoint: http://localhost:4317
          endpoint: http://localhost:4318/v1/traces
          #endpoint: http://localhost:4318
      metrics:
        export:
            #url: http://localhost:4317 
            url: http://localhost:4318/v1/metrics
            #url: http://localhost:4318
            #step: 10s