
#log properties
logging:
  level:
    org:
      springframework: ${LOG:DEBUG}
      #security: ${SEC_LOG:INFO}
    es:
      once:
        newsop: ${ASP_LOG:DEBUG}
logging.level.org.springframework.security: ${SEC_LOG:DEBUG}
logger:
   org.hibernate.SQL: ${HIB_LOG:INFO}
#Apic doc properties
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui # swagger custom path
    enabled: true  # Disabling the swagger-ui production enviroments always false
    use-root-path: true
    groups-order: DESC
    disable-swagger-default-url: true
  #packagesToScan: com.archetype.app.cmd.api.controllers, com.archetype.app.cmd.api.command
  #pathsToMatch: /v1, /**
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: prototypeactions
      username: ${DATASOURCE_USERNAME:admin}
      password: ${DATASOURCE_PASSWORD:adminpw}
      authentication-database: admin
      auto-index-creation: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: "prototype_availability" 

     