version: '3.8'
services:

##########################################################################     
#keycloack-adapter-service
##########################################################################  
  keycloack-adapter-service:
        container_name: keycloack-adapter-service
        build:
            dockerfile: Dockerfile
            context: ./   
        #image: sorteo/keycloackadapter:0.0.1-SNAPSHOT
        environment:
          - JAVA_OPTS=
             -Xms256M 
             -Xmx256M
          - KEYCLOACK_SERVER=http://keycloak_web:8080/realms/
          - KEYCLOACK_REALM=prototype-services
          - KEYCLOACK_REAL_ID=Y82-29HCSoOrSZQH6XRCufMBmz36JqrKT2Dxxa3wesw
          - KEYCLOACK_SECRET=JxgiUkHSDvweVo6v3nAXsOnA2O9CRvz3
          - KEYCLOACK_CLIENT=bff-service
          #-Dspring.profiles.active=docker
        ports:
         - 8092:8092    
        networks:
         - kraken-net
networks:
    kraken-net:
        name: kraken-net
        driver: bridge