server:
  port: 8083
---
spring:
  cloud:
    function:
      #definition: supplier;consumer
      definition: processor   
    stream:
      #function:
        #definition: processor
      bindings:
        processor-in-0:
          destination: order-created
        processor-out-0:
          destination: order-updated
      kafka:
        binder:
          replication-factor: 1
          brokers: localhost:9092
---
service:
  endpoints:
    inventory: http://localhost:8081
    payment: http://localhost:8082